config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root 'welcome#index'
  get 'welcome/index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def new
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        
        @recipe.save
        redirect_to @recipe
    end
    
    def show
        @recipe = Recipe.find(params[:id])
    end
    
    private
        def recipe_params
            params.require(:recipe).permit(:title, :instruction)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/new.html.erb
<%= form_for :recipe,url: recipes_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :instruction %><br>
    <%= f.text_area :instruction %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/recipes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>
 
<p>
  <strong>Instructions:</strong>
  <%= @recipe.instruction %>
</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>